---
- hosts: all
  become: true
  tasks:
    
  -  name: install php and apache Ubuntu
     apt:
       name: 
         - apache2
         - libapache2-mod-php
       state: latest
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

  -  name: install php and apache CentOS
     yum:
       name: 
         - httpd
         - php
       state: latest
       update_cache: yes
     when: ansible_distribution == "CentOS"
  
