- hosts: all
  become: true
  tasks:
 

   # Install apache and php
  -  name: install apache and php
     package:
       name:
         - "{{ apache_package }}"
         - "{{ php_package }}"
       state: latest
       update_cache: yes