---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip


  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  

- hosts: web_servers
  become: true
  tasks:

  -  name: install apache2 and php package (Ubuntu)
     apt:
       name: 
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

  -  name: install apache2 and php package (CentOS)
     yum:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb package (CentOS)
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:
    - name: Install samba package
      package:
        name: samba
        state: latest