- hosts: web_servers
  become: yes
  tasks:

  - name: Remove Apache (centOS)
    tags: remove, apache
    yum:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"
    
       