---

- hosts: all
  become: true
  tasks:

  -  name: install apache2 package
     apt:
       name: apache2
       state: latest
     when: ansible_nodename == "svcl-02"

  -  name: update repostiroy index
     apt:
       update_cache=yes
     

  -  name: add php support for apache
     apt:
       name: libapache2-mod-php
       state: latest
     when: ansible_nodename == "svcl-02"
